### Register User
POST http://localhost:5000/api/auth/register 
Content-Type: application/json

{
  "name": "Test Employee",
  "email": "asdf@mern.com",
  "password": "1234567",
  "role": "employee"
}
